In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("archive\comptab_2018-01-29 16_00_comma_separated.csv")

In [3]:
data

,Year,App.,Taxon,Class,Order,Family,Genus,Importer,Exporter,Origin,Importer reported quantity,Exporter reported quantity,Term,Unit,Purpose,Source
0,2016,I,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,TR,NL,CZ,NaN,1.0,bodies,NaN,T,C
1,2016,I,Aquila heliaca,Aves,Falconiformes,Accipitridae,Aquila,XV,RS,RS,NaN,1.0,bodies,NaN,Q,O
2,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,NaN,43.0,feathers,NaN,S,W
3,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,BE,NO,NaN,NaN,43.0,specimens,NaN,S,W
4,2016,I,Haliaeetus albicilla,Aves,Falconiformes,Accipitridae,Haliaeetus,DK,IS,NaN,700.0,NaN,specimens,NaN,S,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67156,2017,III,Canis aureus,Mammalia,Carnivora,Canidae,Canis,US,ET,NaN,NaN,7.0,trophies,NaN,H,W
67157,2017,III,Sarcoramphus papa,Aves,Falconiformes,Cathartidae,Sarcoramphus,JP,PE,NaN,NaN,2.0,live,NaN,T,F
67158,2017,III,Daboia russelii,Reptilia,Serpentes,Viperidae,Daboia,RS,IT,US,200.0,NaN,specimens,NaN,T,F
67159,2017,III,Civettictis civetta,Mammalia,Carnivora,Viverridae,Civettictis,FR,ET,NaN,NaN,635.1,musk,kg,T,R
67160,2017,III,Civettictis civetta,Mammalia,Carnivora,Viverridae,Civettictis,KR,ET,NaN,NaN,480.0,musk,kg,T,R

In [4]:
data.columns

Index(['Year', 'App.', 'Taxon', 'Class', 'Order', 'Family', 'Genus',
       'Importer', 'Exporter', 'Origin', 'Importer reported quantity',
       'Exporter reported quantity', 'Term', 'Unit', 'Purpose', 'Source'],
      dtype='object')

In [8]:
len(data.columns)

16

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67161 entries, 0 to 67160
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        67161 non-null  int64
 1   App.                        67161 non-null  object
 2   Taxon                       67161 non-null  object
 3   Class                       46937 non-null  object
 4   Order                       67104 non-null  object
 5   Family                      66700 non-null  object
 6   Genus                       65702 non-null  object
 7   Importer                    67090 non-null  object
 8   Exporter                    66588 non-null  object
 9   Origin                      25643 non-null  object
 10  Importer reported quantity  31866 non-null  float64
 11  Exporter reported quantity  44021 non-null  float64
 12  Term                        67161 non-null  object
 13  Unit                        6402 non-null   object
 14  Purpose                     61102 non-null  object
 15  Source                      66617 non-null  object
dtypes: float64(2), int64(1), object(13)
memory usage: 8.2+ MB

In [11]:
data['Year'].unique()

array([2016, 2017], dtype=int64)

In [12]:
data['App.'].unique()

array(['I', 'II', 'III', 'N'], dtype=object)

In [20]:
for i in data.columns:
    print("***************")
    print(i)
    print(data[i].unique())

***************
Year
[2016 2017]
***************
App.
['I' 'II' 'III' 'N']
***************
Taxon
['Aquila heliaca' 'Haliaeetus albicilla' 'Harpia harpyja' ...
 'Phaethornis malaris' 'Phaethornis ruber' 'Threnetes niger']
***************
Class
['Aves' 'Actinopteri' 'Mammalia' 'Reptilia' nan 'Amphibia' 'Coelacanthi'
 'Elasmobranchii' 'Bivalvia' 'Anthozoa' 'Hirudinoidea' 'Hydrozoa'
 'Dipneusti' 'Insecta' 'Arachnida' 'Gastropoda' 'Holothuroidea']
***************
Order
['Falconiformes' 'Acipenseriformes' 'Carnivora' 'Crocodylia'
 'Anseriformes' 'Artiodactyla' 'Gentianales' 'Pinales' 'Primates'
 'Cetacea' 'Serpentes' 'Coraciiformes' 'Anura' 'Psittaciformes'
 'Caryophyllales' 'Testudines' 'Ciconiiformes' 'Columbiformes' 'Asterales'
 'Caudata' 'Sirenia' 'Proboscidea' 'Perissodactyla' 'Euphorbiales'
 'Passeriformes' 'Gruiformes' 'Sauria' 'Coelacanthiformes' 'Fabales'
 'Liliales' 'Nepenthales' 'Orchidales' 'Osteoglossiformes' 'Galliformes'
 'Pristiformes' 'Chiroptera' 'Perciformes' 'Charadriiformes'
 'Sphenisciformes' 'Cycadales' 'Struthioniformes' 'Peramelemorphia'
 'Apodiformes' 'Trogoniformes' 'Unionoida' nan 'Scleractinia' 'Sapindales'
 'Anguilliformes' 'Antipatharia' 'Apiales' 'Ranunculales' 'Pilosa'
 'Bromeliales' 'Carcharhiniformes' 'Violales' 'Cyatheales' 'Dicksoniales'
 'Ebenales' 'Helioporacea' 'Arhynchobdellida' 'Lamniformes' 'Laurales'
 'Pholidota' 'Milleporina' 'Cuculiformes' 'Myliobatiformes'
 'Ceratodontiformes' 'Scrophulariales' 'Arecales' 'Lepidoptera'
 'Diprotodontia' 'Primulales' 'Piciformes' 'Rheiformes' 'Orectolobiformes'
 'Rosales' 'Rodentia' 'Scorpiones' 'Strigiformes' 'Mesogastropoda'
 'Stylasterina' 'Syngnathiformes' 'Monotremata' 'Araneae' 'Myrtales'
 'Veneroida' 'Stolonifera' 'Scandentia' 'Dipsacales' 'Rhamnales'
 'Gorgonacea' 'Fagales' 'Lamiales' 'Aspidochirotida' 'Arales' 'Ericales'
 'Archaeogastropoda' 'Lycopodiales' 'Solanales' 'Lecanorales'
 'Selaginellales']
***************
Family
['Accipitridae' 'Acipenseridae' 'Ailuridae' 'Alligatoridae' 'Anatidae'
 'Antilocapridae' 'Apocynaceae' 'Araucariaceae' 'Atelidae' 'Balaenidae'
 'Balaenopteridae' 'Boidae' 'Bovidae' 'Bucerotidae' 'Bufonidae'
 'Cacatuidae' 'Cactaceae' 'Camelidae' 'Canidae' 'Cathartidae' 'Cebidae'
 'Cercopithecidae' 'Cervidae' 'Cheirogaleidae' 'Chelidae' 'Cheloniidae'
 'Ciconiidae' 'Columbidae' 'Compositae' 'Crocodylidae' 'Cryptobranchidae'
 'Delphinidae' 'Dermochelyidae' 'Dugongidae' 'Elephantidae' 'Equidae'
 'Eschrichtiidae' 'Euphorbiaceae' 'Falconidae' 'Felidae' 'Fringillidae'
 'Gavialidae' 'Geoemydidae' 'Gruidae' 'Helodermatidae' 'Hominidae'
 'Hylobatidae' 'Iguanidae' 'Indriidae' 'Latimeriidae' 'Leguminosae'
 'Lemuridae' 'Lepilemuridae' 'Liliaceae' 'Lorisidae' 'Loxocemidae'
 'Moschidae' 'Muscicapidae' 'Mustelidae' 'Nepenthaceae' 'Orchidaceae'
 'Osteoglossidae' 'Otididae' 'Phasianidae' 'Phocoenidae' 'Physeteridae'
 'Pitheciidae' 'Pristidae' 'Psittacidae' 'Pteropodidae' 'Pythonidae'
 'Rhinocerotidae' 'Sarraceniaceae' 'Sciaenidae' 'Scolopacidae'
 'Spheniscidae' 'Stangeriaceae' 'Struthionidae' 'Sturnidae' 'Tapiridae'
 'Testudinidae' 'Threskiornithidae' 'Thylacomyidae' 'Trichechidae'
 'Trochilidae' 'Trogonidae' 'Unionidae' 'Ursidae' 'Varanidae' 'Zamiaceae'
 'Ziphiidae' nan 'Acroporidae' 'Agamidae' 'Agariciidae' 'Agavaceae'
 'Amaryllidaceae' 'Ambystomatidae' 'Anacardiaceae' 'Anguillidae'
 'Antipathidae' 'Aotidae' 'Aphanipathidae' 'Araliaceae' 'Arapaimidae'
 'Aromobatidae' 'Astrocoeniidae' 'Balaenicipitidae' 'Berberidaceae'
 'Bradypodidae' 'Bromeliaceae' 'Carcharhinidae' 'Carettochelyidae'
 'Caryophylliidae' 'Chamaeleonidae' 'Cladopathidae' 'Colubridae'
 'Cordylidae' 'Cotingidae' 'Cucurbitaceae' 'Cyatheaceae' 'Cycadaceae'
 'Dendrobatidae' 'Dendrophylliidae' 'Dicksoniaceae' 'Dicroglossidae'
 'Didiereaceae' 'Dioscoreaceae' 'Droseraceae' 'Ebenaceae' 'Elapidae'
 'Emberizidae' 'Emydidae' 'Estrildidae' 'Eupleridae' 'Faviidae'
 'Flabellidae' 'Fungiacyathidae' 'Fungiidae' 'Galagidae' 'Gekkonidae'
 'Helioporidae' 'Hippopotamidae' 'Hirudinidae' 'Hylidae' 'Iniidae'
 'Labridae' 'Lacertidae' 'Lamnidae' 'Lauraceae' 'Leiopathidae' 'Loriidae'
 'Manidae' 'Mantellidae' 'Meandriniidae' 'Meliaceae' 'Merulinidae'
 'Milleporidae' 'Monodontidae' 'Musophagidae' 'Mussidae' 'Myliobatidae'
 'Myriopathidae' 'Myrmecophagidae' 'Neoceratodontidae' 'Oculinidae'
 'Orobanchaceae' 'Otariidae' 'Palmae' 'Pandionidae' 'Papilionidae'
 'Paradisaeidae' 'Passifloraceae' 'Pectiniidae' 'Pedaliaceae'
 'Phalangeridae' 'Phocidae' 'Phoenicopteridae' 'Pocilloporidae'
 'Podocnemididae' 'Polyodontidae' 'Poritidae' 'Portulacaceae'
 'Primulaceae' 'Pycnonotidae' 'Ramphastidae' 'Ranunculaceae' 'Rheidae'
 'Rhincodontidae' 'Rhizangiidae' 'Rosaceae' 'Sagittariidae'
 'Schizopathidae' 'Scincidae' 'Sciuridae' 'Scorpionidae'
 'Scrophulariaceae' 'Siderastreidae' 'Sphyrnidae' 'Strigidae' 'Strombidae'
 'Stylasteridae' 'Syngnathidae' 'Tachyglossidae' 'Tarsiidae' 'Taxaceae'
 'Tayassuidae' 'Teiidae' 'Theraphosidae' 'Thymelaeaceae'
 'Trachyphylliidae' 'Tridacnidae' 'Trionychidae' 'Tropidophiidae'
 'Tubiporidae' 'Tupaiidae' 'Tytonidae' 'Valerianaceae' 'Viperidae'
 'Vitaceae' 'Viverridae' 'Xenosauridae' 'Zygophyllaceae' 'Burhinidae'
 'Calyptocephalellidae' 'Chelydridae' 'Coralliidae' 'Cracidae'
 'Cuniculidae' 'Dasyproctidae' 'Fagaceae' 'Hyaenidae' 'Megalonychidae'
 'Nymphalidae' 'Odobenidae' 'Oleaceae' 'Procyonidae' 'Stichopodidae'
 'Anguidae' 'Apogonidae' 'Araceae' 'Ardeidae' 'Ericaceae' 'Gentianaceae'
 'Gerrhosauridae' 'Haliotidae' 'Hydrophiidae' 'Hystricidae'
 'Lycopodiaceae' 'Menyanthaceae' 'Parmeliaceae' 'Salamandridae'
 'Selaginellaceae']
***************
Genus
['Aquila' 'Haliaeetus' 'Harpia' ... 'Heliodoxa' 'Leucippus' 'Threnetes']
***************
Importer
['TR' 'XV' 'BE' 'DK' 'BR' 'CH' 'US' 'AU' 'CA' 'IL' 'JP' 'KP' 'KR' 'MC'
 'GB' 'CN' 'SG' 'ZA' 'NL' 'DE' 'AT' 'NO' 'RU' 'FR' 'XX' 'FO' 'IS' 'ES'
 'SE' 'ID' 'IR' 'AR' 'HU' 'IT' 'MX' 'OM' 'PK' 'VN' 'AE' 'BY' 'FI' 'PH'
 'UZ' 'TN' 'PT' 'CZ' 'LT' 'RS' 'SK' 'TD' 'KW' 'QA' 'SA' 'TW' 'TZ' 'BH'
 'TH' 'BS' 'CR' 'KG' 'KZ' 'SR' 'NZ' 'PA' 'BG' 'GR' 'IN' 'HK' 'PL' 'RO'
 'NP' 'MY' 'JE' 'MD' 'BB' 'RE' 'PE' 'PF' 'CU' 'SN' 'BD' 'CO' 'EG' 'MA'
 'SZ' 'AM' 'AZ' 'BL' 'UA' 'UG' 'BN' 'CG' 'LB' 'MO' 'TM' 'CY' 'MG' 'CL'
 'GG' 'IE' 'KY' 'LI' 'GE' 'BA' 'BM' 'BW' 'ET' 'GL' 'JO' 'KE' 'KH' 'PG'
 'UY' 'ZW' 'MN' 'GI' 'IQ' 'SI' 'SD' 'MM' 'EE' 'HR' 'LU' 'LV' nan 'TJ' 'EC'
 'CD' 'GT' 'TT' 'IM' 'MK' 'PY' 'MU' 'NC' 'AF' 'CW' 'GF' 'ME' 'SX' 'AW'
 'CI' 'GP' 'MQ' 'MV' 'LK' 'DZ' 'AO' 'NI' 'DO' 'GH' 'AG' 'KN' 'AD' 'AL'
 'AN' 'BJ' 'CM' 'DJ' 'GA' 'HN' 'LA' 'LC' 'MR' 'MW' 'SC' 'SM' 'SV' 'VA'
 'VE' 'VG' 'BO' 'BZ' 'CC' 'ER' 'FJ' 'GD' 'GN' 'GU' 'GY' 'HT' 'JM' 'LR'
 'LY' 'MF' 'MP' 'MT' 'MZ' 'NG' 'PR' 'TC' 'TG' 'TL' 'VI' 'ML' 'SU' 'NE'
 'BQ' 'CV' 'GM' 'YE' 'YU' 'ZM' 'BF' 'YT' 'PW' 'WS' 'VC' 'KI' 'SY' 'CF'
 'TK' 'DM' 'GQ' 'TF' 'AI' 'RW']
***************
Exporter
['NL' 'RS' 'NO' 'IS' 'FR' 'DE' 'IR' 'NZ' 'US' 'CN' 'JP' 'CA' 'DK' 'JE'
 'GB' 'CH' 'BE' 'TH' 'CL' 'IT' 'PE' 'GL' 'RU' 'TN' 'ZZ' 'CV' 'AU' 'FI'
 'SE' 'XX' 'AQ' 'MX' 'VC' 'MG' 'OM' nan 'QA' 'AE' 'SK' 'TJ' 'PK' 'BY' 'LA'
 'ES' 'ZA' 'PL' 'BR' 'DO' 'BH' 'PH' 'PT' 'IL' 'SG' 'KZ' 'BS' 'UZ' 'KW'
 'MT' 'HK' 'CZ' 'HU' 'KH' 'AT' 'AR' 'LT' 'TZ' 'VN' 'GG' 'MC' 'LB' 'BM'
 'KY' 'NI' 'PA' 'UY' 'ST' 'CR' 'FJ' 'HT' 'KR' 'TO' 'BZ' 'CO' 'FM' 'JM'
 'LC' 'MH' 'PW' 'SV' 'TR' 'VE' 'CU' 'ET' 'TW' 'VG' 'GD' 'MV' 'IN' 'MY'
 'UG' 'SN' 'SD' 'ZM' 'MO' 'BD' 'RO' 'CD' 'NG' 'KN' 'LI' 'IE' 'GR' 'ID'
 'KE' 'SL' 'GE' 'MM' 'UA' 'LK' 'MZ' 'AD' 'SI' 'CI' 'ZW' 'CM' 'LU' 'SA'
 'SZ' 'MN' 'MA' 'BG' 'JO' 'AM' 'MU' 'AZ' 'BO' 'EC' 'PY' 'CF' 'ML' 'EE'
 'NC' 'YE' 'KG' 'RW' 'CG' 'GA' 'IQ' 'GI' 'LV' 'SR' 'KM' 'HR' 'FK' 'GS'
 'PG' 'GQ' 'LS' 'CY' 'MD' 'CK' 'AG' 'CW' 'SB' 'IO' 'EG' 'BJ' 'GH' 'TG'
 'AL' 'BL' 'XV' 'BB' 'NE' 'SX' 'TC' 'GY' 'GT' 'ER' 'MK' 'LR' 'DM' 'GW'
 'IM' 'TD' 'GN' 'MW' 'FO' 'HN' 'BW' 'SH' 'SM' 'DD' 'SC' 'TT' 'SY' 'BI'
 'NP' 'TL' 'PF' 'GP' 'VU' 'AN' 'AW' 'KP' 'TK' 'KI' 'WS' 'GM' 'BA' 'ME'
 'AO']
***************
Origin
['CZ' 'RS' nan 'XX' 'GB' 'CL' 'GL' 'RU' 'US' 'BR' 'DK' 'ES' 'NO' 'FK' 'FR'
 'DE' 'BY' 'PK' 'TJ' 'AO' 'ZA' 'BH' 'AT' 'CA' 'BE' 'AR' 'HU' 'IT' 'PH'
 'PE' 'BO' 'NL' 'PL' 'MG' 'AU' 'NI' 'PF' 'CU' 'JM' 'IN' 'CN' 'CO' 'SN'
 'MZ' 'ZW' 'IL' 'MY' 'TH' 'SG' 'ZM' 'PG' 'VN' 'KH' 'JP' 'KE' 'UA' 'CX'
 'ZZ' 'KR' 'TZ' 'CD' 'BW' 'SD' 'CI' 'CH' 'CG' 'BF' 'CF' 'CM' 'GA' 'LR'
 'LY' 'RW' 'SL' 'SO' 'TD' 'GN' 'GQ' 'HK' 'EE' 'AE' 'XV' 'PT' 'SK' 'IE'
 'SI' 'IQ' 'CV' 'GE' 'MA' 'ID' 'LA' 'SA' 'UZ' 'TW' 'EC' 'FJ' 'GM' 'SY'
 'SE' 'LC' 'MT' 'SR' 'LU' 'MU' 'NC' 'JE' 'NG' 'MX' 'AM' 'FI' 'BG' 'GR'
 'UY' 'IR' 'TO' 'SB' 'FM' 'ML' 'TG' 'BJ' 'AL' 'VE' 'PY' 'GY' 'HN' 'PA'
 'GT' 'TR' 'DM' 'GH' 'KG' 'KZ' 'JO' 'DO' 'LB' 'RO' 'OM' 'LV' 'BS' 'BB'
 'KN' 'MN' 'MR' 'LT' 'MW' 'UG' 'BD' 'SU' 'TF' 'EG' 'VU' 'NZ' 'CR' 'VC'
 'AQ' 'VG' 'ST' 'MK' 'MH' 'SV' 'CW' 'BZ' 'NP' 'MM' 'IO' 'SC' 'LK' 'MD'
 'BM' 'BN' 'CK' 'KI' 'PW' 'KY' 'NE' 'IS' 'MV' 'GS' 'ET']
***************
Importer reported quantity
[    nan  700.    100.   ... 1566.    151.14   35.2 ]
***************
Exporter reported quantity
[1.000e+00 4.300e+01       nan ... 6.580e+03 5.230e+03 6.351e+02]
***************
Term
['bodies' 'feathers' 'specimens' 'live' 'caviar' 'skins' 'seeds' 'hair'
 'carvings' 'baleen' 'bone pieces' 'bone carvings' 'teeth' 'skin pieces'
 'meat' 'bones' 'jewellery' 'skeletons' 'trophies' 'horns' 'skulls'
 'fur product (small)' 'garments' 'dried plants' 'extract' 'cloth'
 'unspecified' 'shells' 'eggshell' 'carapaces' 'leather products (small)'
 'oil' 'eggs' 'scales' 'genitalia' 'medicine' 'roots' 'powder'
 'derivatives' 'leather products (large)' 'rug' 'tails' 'cosmetics'
 'ivory carvings' 'ivory pieces' 'piano keys' 'tusks' 'jewellery - ivory '
 'feet' 'ears' 'claws' 'eggs (live)' 'wood product' 'sawn wood' 'veneer'
 'musk' 'cultures' 'stems' 'flowers' 'fins' 'horn carvings' 'horn pieces'
 'swim bladders' 'gall' 'coral sand' 'fingerlings' 'raw corals' 'sides'
 'plates' 'leaves' 'fibres' 'timber' 'hair products'
 'fur products (large)' 'chips' 'trunk' 'wax' 'logs' 'pupae'
 'gall bladders' 'bark' 'fruit' 'pearl']
***************
Unit
[nan 'g' 'kg' 'ml' 'm2' 'mg' 'l' 'cm3' 'm3' 'cm2' 'm' 'microgrammes'
 'metric tonnes' 'cm']
***************
Purpose
['T' 'Q' 'S' 'P' 'Z' 'B' 'E' 'H' 'N' 'L' 'M' nan 'G']
***************
Source
['C' 'O' 'W' 'U' 'I' 'F' 'D' 'A' 'X' nan 'R']

In [ ]:
q